# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCoinbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
            ],
        ),
    ]
