# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatchAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiLatch',
        ),
    ]
