# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase', '0002_auto_20170817_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='latchaccess',
            name='fixed_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
